[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma db push --skip-generate && npx tsx src/index.ts"
